# Generated by Django 2.2.28 on 2022-08-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_test123m'),
    ]

    operations = [
        migrations.AddField(
            model_name='test123m',
            name='ddswx',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
