# Generated by Django 2.2.28 on 2022-08-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_test123m_ddswx'),
    ]

    operations = [
        migrations.AddField(
            model_name='test123m',
            name='wqswqs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
